[package]
name = "rsgen-avro"
version = "0.6.4-6"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
description = "Command line and library for generating Rust types from Avro schemas"
keywords = ["avro", "code-generation", "serde"]
repository = "https://github.com/lerouxrgd/rsgen-avro"
license = "MIT"
readme = "README.md"

[dependencies]
avro-rs = "0.7"
docopt = "1"
failure = "0.1"
heck = "0.3"
lazy_static = "1.4"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
tera = "1.1"
thiserror = "1.0"

[dev-dependencies]
matches = "0.1"